// Decoy relay nodes (proxychains origins), generated by scripts/gen-worldmap.mjs.
// Edit that script and regenerate rather than hand-editing this file.
export type Relay = {
  city: string;
  region: string;
  decimal: string;
  dms: string;
  cell: { row: number; col: number };
};
export const RELAYS: Relay[] = [
  {
    "city": "REYKJAVIK",
    "region": "REYKJAVIK, IS",
    "decimal": "64.146600, -21.942600",
    "dms": "64°08'48\"N 21°56'33\"W",
    "cell": {
      "row": 1,
      "col": 29
    }
  },
  {
    "city": "MONTREAL",
    "region": "MONTREAL, CA",
    "decimal": "45.501900, -73.567400",
    "dms": "45°30'07\"N 73°34'03\"W",
    "cell": {
      "row": 10,
      "col": 20
    }
  },
  {
    "city": "SAO PAULO",
    "region": "SAO PAULO, BR",
    "decimal": "-23.555800, -46.639600",
    "dms": "23°33'21\"S 46°38'23\"W",
    "cell": {
      "row": 25,
      "col": 26
    }
  },
  {
    "city": "LAGOS",
    "region": "LAGOS, NG",
    "decimal": "6.524400, 3.379200",
    "dms": "6°31'28\"N 3°22'45\"E",
    "cell": {
      "row": 19,
      "col": 36
    }
  },
  {
    "city": "ZURICH",
    "region": "ZURICH, CH",
    "decimal": "47.376900, 8.541700",
    "dms": "47°22'37\"N 8°32'30\"E",
    "cell": {
      "row": 10,
      "col": 38
    }
  },
  {
    "city": "TOKYO",
    "region": "TOKYO, JP",
    "decimal": "35.676200, 139.650300",
    "dms": "35°40'34\"N 139°39'01\"E",
    "cell": {
      "row": 11,
      "col": 63
    }
  },
  {
    "city": "SINGAPORE",
    "region": "SINGAPORE, SG",
    "decimal": "1.352100, 103.819800",
    "dms": "1°21'08\"N 103°49'11\"E",
    "cell": {
      "row": 17,
      "col": 57
    }
  },
  {
    "city": "SYDNEY",
    "region": "SYDNEY, AU",
    "decimal": "-33.868800, 151.209300",
    "dms": "33°52'08\"S 151°12'33\"E",
    "cell": {
      "row": 28,
      "col": 66
    }
  }
];
